language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
before_install:
    - sudo apt-get install python3-pandas python3-scipy
install:
  - pip install .
script: 
  - py.test tests
